"""add_system_integration_extend_fields

Revision ID: 011_system_integration_fields
Revises: 010_system_integration_extend
Create Date: 2025-04-01 00:01:00.000000

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '011_system_integration_fields'
down_revision = '010_system_integration_extend'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'system_integration_extend' not in tables:
        return

    existing_columns = {c['name'] for c in inspector.get_columns('system_integration_extend')}
    columns_to_add = []

    if 'test' not in existing_columns:
        columns_to_add.append(
            sa.Column('test', sa.Boolean(), server_default=sa.text('false'), nullable=True, comment='是否测试链接联通性')
        )
    if 'config' not in existing_columns:
        columns_to_add.append(sa.Column('config', sa.Text(), nullable=True, comment='其他配置'))
    if 'app_id' not in existing_columns:
        columns_to_add.append(sa.Column('app_id', sa.Text(), nullable=True, comment='应用ID'))

    if columns_to_add:
        with op.batch_alter_table('system_integration_extend', schema=None) as batch_op:
            for col in columns_to_add:
                batch_op.add_column(col)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    if 'system_integration_extend' not in inspector.get_table_names():
        return
    existing_columns = {c['name'] for c in inspector.get_columns('system_integration_extend')}
    columns_to_drop = [c for c in ('app_id', 'config', 'test') if c in existing_columns]
    if columns_to_drop:
        with op.batch_alter_table('system_integration_extend', schema=None) as batch_op:
            for col_name in columns_to_drop:
                batch_op.drop_column(col_name)
    # ### end Alembic commands ### 