[build-system]
requires = ["setuptools>=80.10.2,<81"]
build-backend = "setuptools.build_meta"

[project]
name = "dify-trace-arize-phoenix"
version = "0.0.1"
dependencies = [
    "arize-phoenix-otel==0.15.0",
]
description = "Dify ops tracing provider (Arize / Phoenix)."

[tool.setuptools.packages.find]
where = ["src"]
